services:
  - type: web
    name: zentra-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: GOOGLE_CLIENT_ID
        value: your-client-id-here
      - key: GOOGLE_CLIENT_SECRET
        value: your-client-secret-here
      - key: GEMINI_API_KEY
        value: your-gemini-api-key-here
